env:
    RCLONE: "ENCRYPTED[91b79bab4f62dc685e4b058be9c7f50b6b04e19b49d9428726222a96975a8d44a32130d90defa269588e5a5abbd56e08]"
    MANIFEST: "https://gitlab.com/OrangeFox/Manifest"
    MANIFEST_BRANCH: "fox_9.0"
    DEVICE: "land"
    DT_LINK: "https://github.com/sarthakroy2002/android_recovery_realme_RMX3171"
    DT_PATH: "device/realme/RMX3171"
    TARGET: "recoveryimage"
    BUILD_TYPE: "eng"
    COMMAND: "git clone https://gitlab.com/OrangeFox/misc/theme bootable/recovery/gui/theme --depth=1"
    COMMAND2: ""
    TG_TOKEN: "ENCRYPTED[6c365afb3cbf7f59c490b558865d4226fc654a96891dc945afcd6f3962ec2fe6bf6a7426d3effbaf495b8f32a3488cbd]"
    TG_CHAT_ID: "ENCRYPTED[3c19d691e5a972c47afeb53e6f923ac291095b5689de6e0023c208f5a514d840bdc86f11a7fee59e2688aa07e2f4daa8]"
    TZ: "Asia/Kolkata"
    DRIVE: "ENCRYPTED[f2618529e5a34a6e81c6d22849abd5c6a83d92ec527c04c2228fb5b233b8ffca9331cda2c251d0cfedf08afba14e41f9]"

task:
  name: "Recovery-Builder"
  timeout_in: 480m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 16G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - mkdir -p /tmp/ccache
       - cd /tmp

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Build_script:
      - bash build.sh
